#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-live-view-cert
  namespace: tanzu-system-ingress
spec:
  subject:
    countries:
    - US
    provinces:
    - California
    localities:
    - San Fransisco
    organizations:
    - vmware
    organizationalUnits:
    - vmware mambg
  secretName: app-live-view-tls
  isCA: false
  dnsNames:
  - appliveview.tap.tanzu.y-compiles.com
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: y-compiles.com
  namespace: tanzu-system-ingress
spec:
  secretName: tls
  privateKey:
      rotationPolicy: Always
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'tap-gui.tap.tanzu.y-compiles.com'
  - 'metadata-store.tap.tanzu.y-compiles.com'
  - '*.learningcenter.tap.tanzu.y-compiles.com'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tls
  namespace: tanzu-system-ingress
spec:
  toNamespace: learningcenter
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tls
  namespace: learningcenter
spec:
  fromNamespace: tanzu-system-ingress