#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: y-compiles.com
  namespace: tanzu-system-ingress
spec:
  commonName: '*.tap.tanzu.y-compiles.com'
  secretName: tls
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.tap.tanzu.y-compiles.com'
  - '*.learningcenter.tap.tanzu.y-compiles.com'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tls
  namespace: tanzu-system-ingress
spec:
  toNamespace: learningcenter
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tls
  namespace: learningcenter
spec:
  fromNamespace: tanzu-system-ingress